version: '3'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://localhost:5010"
      NODE_ENV: "development"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
